export const SEARCH_FOCUS = 'header/SEARCH_FOCUS'
export const SEARCH_BLUR = 'header/SEARCH_BLUR'
export const CHANG_LIST = 'header/CHANG_LIST'
export const CHANGE_ENTER = 'header/CHANGE_ENTER'
export const CHANGE_LEAVE = 'header/CHANGE_LEAVE'
export const CHANGE_PAGE = 'header/CHANGE_PAGE'
